# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yalchat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_e54edeb3558947869db226130f016b95 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2777e28bd4894a65bf850b897dc27e19 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e54edeb3558947869db226130f016b95 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yalchat'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b83ed06d28314098b23baa1fc077204b }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e54edeb3558947869db226130f016b95 }}/appsvc/staticsite:${{ github.sha }}'